name: Deploy
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install node
              uses: actions/setup-node@v4
              with:
                node-version: 21
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install node
              uses: actions/setup-node@v4
              with:
                node-version: 21
            - name: Install dependencies
              run: npm ci
            - name: Test
              run: npm run test
    build:
        needs: test
        runs-on: ubuntu-latest
        outputs:
            script-file: ${{ steps.publish-js-filename.outputs.script-file }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install node
              uses: actions/setup-node@v4
              with:
                node-version: 21
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Publish js filename
              id: publish-js-filename
              run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
            - name: Upload artifacts
              uses: actions/upload-artifact@v4 
              with:
                name: dist-files
                path: dist
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Get build artifacts
              uses: actions/download-artifact@v4
              with:
                name: dist-files
            - name: Output dist-files contents
              run: ls -lR
            - name: Output filename
              run: echo "script [${{ needs.build.outputs.script-file }}]"
            - name: Deploy
              run: echo "Deploying..."
            
        
