name: Issues
on:
    issues:
        types: [opened]
jobs:
    output-event-details:
        runs-on: ubuntu-latest
        steps:
            - name: Output event details
              run: echo ${{ github.event }}
